### PR TITLE
Prepare v2.0.0

### PR DESCRIPTION
**Pull request by jrick**
Updates dcrd to release-v2.0.0 tag.

Updates dcrwallet to release-v2.0.0 tag.

Updates dcrctl to release-v2.0.0 tag.

Updates dcrlnd to v0.7.0 tag.

### CODE REVIEW

**Comment by jrick** [comment]
`2024/05/16 17:50:34 dist "dcrinstall-manifests" manifest hash: SHA256:dd9cd276b96cc88ab42cfcc917d5838f963bb28a8fd1a27aa6099330932b787b (go version go1.22.3 linux/amd64)`

`2024/05/16 17:54:47 dist "dcrinstall-manifests" manifest hash: SHA256:dd9cd276b96cc88ab42cfcc917d5838f963bb28a8fd1a27aa6099330932b787b (go version go1.22.3 openbsd/amd64)`

```
elsa$ sh ./showvers.sh                                                                                                                                                                                                                                                            
dcrd version 2.0.0+release (Go version go1.22.3 linux/amd64)
dcrctl version 2.0.0+release (Go version go1.22.3 linux/amd64)
dcrwallet version 2.0.0+release (Go version go1.22.3 linux/amd64)
dexc version 0.6.3+release (Go version go1.22.3 linux/amd64)
dexcctl version 0.6.3+release (Go version go1.22.3 linux/amd64)
dexcctl required RPC server version: 0.3.0
dcrlncli version 0.7.0+release (Go version go1.22.3 linux/amd64)

dcrlnd version 0.7.0+release (Go version go1.22.3 linux/amd64)
WARNING: ./bin/linux-amd64/dexc-tray is not built
dexcctl version 0.6.3+release (Go version go1.22.3 linux/amd64)
dexcctl required RPC server version: 0.3.0
politeiavoter version 1.4.0+release (Go version go1.22.3 linux/amd64)
```

**Comment by davecgh** [comment]
```
windows: dist "dcrinstall-manifests" manifest hash: SHA256:dd9cd276b96cc88ab42cfcc917d5838f963bb28a8fd1a27aa6099330932b787b (go version go1.22.3 windows/amd64)
  linux: dist "dcrinstall-manifests" manifest hash: SHA256:dd9cd276b96cc88ab42cfcc917d5838f963bb28a8fd1a27aa6099330932b787b (go version go1.22.3 linux/amd64)
```

Windows versions:

```
$ sh ./showvers.sh
dcrd version 2.0.0+release (Go version go1.22.3 windows/amd64)
dcrctl version 2.0.0+release (Go version go1.22.3 windows/amd64)
dcrwallet version 2.0.0+release (Go version go1.22.3 windows/amd64)
dexc version 0.6.3+release (Go version go1.22.3 windows/amd64)
dexcctl version 0.6.3+release (Go version go1.22.3 windows/amd64)
dexcctl required RPC server version: 0.3.0
dcrlncli version 0.7.0+release (Go version go1.22.3 windows/amd64)
dcrlnd version 0.7.0+release (Go version go1.22.3 windows/amd64)
dexc version 0.6.3+release (Go version go1.22.3 windows/amd64)
dexcctl version 0.6.3+release (Go version go1.22.3 windows/amd64)
dexcctl required RPC server version: 0.3.0
politeiavoter version 1.4.0+release (Go version go1.22.3 windows/amd64)
```

Windows versions:
```
$ sh ./showvers.sh
dcrd version 2.0.0+release (Go version go1.22.3 linux/amd64)
dcrctl version 2.0.0+release (Go version go1.22.3 linux/amd64)
dcrwallet version 2.0.0+release (Go version go1.22.3 linux/amd64)
dexc version 0.6.3+release (Go version go1.22.3 linux/amd64)
dexcctl version 0.6.3+release (Go version go1.22.3 linux/amd64)
dexcctl required RPC server version: 0.3.0
dcrlncli version 0.7.0+release (Go version go1.22.3 linux/amd64)
dcrlnd version 0.7.0+release (Go version go1.22.3 linux/amd64)
dexc version 0.6.3+release (Go version go1.22.3 linux/amd64)
dexcctl version 0.6.3+release (Go version go1.22.3 linux/amd64)
dexcctl required RPC server version: 0.3.0
politeiavoter version 1.4.0+release (Go version go1.22.3 linux/amd64)
```

**Review by davecgh — APPROVED** [review]

**Comment by jrick** [comment]
I reproduce same build on darwin/amd64.

`2024/05/16 19:14:48 dist "dcrinstall-manifests" manifest hash: SHA256:dd9cd276b96cc88ab42cfcc917d5838f963bb28a8fd1a27aa6099330932b787b (go version go1.22.3 darwin/amd64)`

**Comment by jrick** [comment]
And from openbsd/arm64:

`2024/05/16 19:54:19 dist "dcrinstall-manifests" manifest hash: SHA256:dd9cd276b96cc88ab42cfcc917d5838f963bb28a8fd1a27aa6099330932b787b (go version go1.22.3 openbsd/arm64)`

**Comment by jholdstock** [comment]
```
dist "dcrinstall-manifests" manifest hash: SHA256:dd9cd276b96cc88ab42cfcc917d5838f963bb28a8fd1a27aa6099330932b787b (go version go1.22.3 linux/amd64)
```

lgtm on linux/amd64

**Review by jholdstock — APPROVED** [review]

**Pull request merged**
