### PR TITLE
Prepare v1.7.0

### PR DESCRIPTION
**Pull request by jrick**
Updates dcrd to release-v1.7.0 tag.

Updates dcrwallet to release-v1.7.0 tag.

Updates dcrctl to release-v1.7.0 tag.

Updates dcrdex and dcrdex-assets to v0.4.0 tags.

Updates dcrlnd to v0.3.4 tag.

### CODE REVIEW

**Review by davecgh — APPROVED** [review]
windows: dist "dcrinstall-manifests" manifest hash: SHA256:250b518903b2b3e5f8d8eacf6b4bd0d1441d41725da566800cee2aa3eb54fa91 (go version go1.17.6 windows/amd64)
  linux: dist "dcrinstall-manifests" manifest hash: SHA256:250b518903b2b3e5f8d8eacf6b4bd0d1441d41725da566800cee2aa3eb54fa91 (go version go1.17.6 linux/amd64)

**Review by matheusd — COMMENTED** [review]
Verified.

```
2022/01/21 11:57:16 dist "dcrinstall-manifests" manifest hash: SHA256:250b518903b2b3e5f8d8eacf6b4bd0d1441d41725da566800cee2aa3eb54fa91 (go version go1.17.6 linux/amd64)
```

**Comment by rstaudt2** [comment]
Verified:
`dist "dcrinstall-manifests" manifest hash: SHA256:250b518903b2b3e5f8d8eacf6b4bd0d1441d41725da566800cee2aa3eb54fa91 (go version go1.17.6 linux/amd64)`

**Comment by jholdstock** [comment]
Verified on debian 11:

```
dist "dcrinstall-manifests" manifest hash: SHA256:250b518903b2b3e5f8d8eacf6b4bd0d1441d41725da566800cee2aa3eb54fa91 (go version go1.17.6 linux/amd64)
```

**Pull request merged**
