### PR TITLE
Prepare v1.7.1

### PR DESCRIPTION
**Pull request by jrick**
Updates dcrd to release-v1.7.1 tag.

Updates dcrwallet to release-v1.7.1 tag.

Updates dcrdex and dcrdex-assets to v0.4.1 tags.

### CODE REVIEW

**Comment by jrick** [comment]
```
2022/02/15 17:00:24 dist "dcrinstall-manifests" manifest hash: SHA256:0c9dc5a5d6e195c967d5247ec0925bdf08c492e5aa10f5f4dba184fdb6328ed8 (go version go1.17.7 openbsd/amd64)
```

**Comment by jrick** [comment]
```
2022/02/15 17:22:37 dist "decred" manifest hash: SHA256:5cfe8c6d06f39ed883b2bc50e080585603fb1e9e2affca94ff57f5cd70cfc769 (go version go1.17.7 openbsd/amd64)
2022/02/15 17:22:37 dist "dexc" manifest hash: SHA256:290b8e9ba6d4e7107501aae9131457cd14a88814ae9bc85d35437ca7a5756793 (go version go1.17.7 openbsd/amd64)
2022/02/15 17:22:37 dist "dcrinstall" manifest hash: SHA256:da8beccfb265f1da5e544c56277d90b17ebbd0548f989a7048191fd4c7b31ee8 (go version go1.17.7 openbsd/amd64)
2022/02/15 17:22:37 dist "dcrinstall-manifests" manifest hash: SHA256:7e919fec4c445ed702c7ad830c86160a976fcad0e93673395d5e1995a8bc2b9c (go version go1.17.7 openbsd/amd64)
```

**Review by davecgh — COMMENTED** [review]
```
dist "dcrinstall-manifests" manifest hash: SHA256:7e919fec4c445ed702c7ad830c86160a976fcad0e93673395d5e1995a8bc2b9c (go version go1.17.7 windows/amd64)
dist "dcrinstall-manifests" manifest hash: SHA256:7e919fec4c445ed702c7ad830c86160a976fcad0e93673395d5e1995a8bc2b9c (go version go1.17.7 linux/amd64)
```

I verified that the dcrd and dcrctl version info is correct too.

**Comment by jholdstock** [comment]
```dist "dcrinstall-manifests" manifest hash: SHA256:7e919fec4c445ed702c7ad830c86160a976fcad0e93673395d5e1995a8bc2b9c (go version go1.17.7 linux/amd64)```

Looks good on Ubuntu 20 and Debian 11

**Review by alexlyp — APPROVED** [review]

**Pull request merged**
